version: 0.2
env:
  parameter-store:
    username: /myapp/docker-credentials/username
    password: /myapp/docker-credentials/password
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install 
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - echo "$username"
      - docker login -u "$username" -p "$password"
      - docker build -t "$username/react-app:latest" .
      - docker push  "$username/react-app:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"

