name: gihub-pipeline


on:
  push:
    branches:
      - "main"




jobs:

  build:
    runs-on: self-hosted

    steps:
      - name: Set up Repository 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Installing depedencies
        run: npm install


      - name: Sonar qube code analysis 
        uses: kitabisa/sonarqube-action@master
        with:
          host: ${{ secrets.SONAR_HOST_URL }}
          login: ${{ secrets.SONAR_TOKEN }}
          projectKey: "github-eks"
        

      - name: File Scan
        run: trivy fs . >  filesystem-analysis.txt


      - name: Image build 
        run: |
          docker build -t inderharrysingh/github-eks .
          docker login -u inderharrysingh -p ${{ secrets.PASS }}
          docker push inderharrysingh/github-eks 


      - name: Image Scan
        run: trivy image  inderharrysingh/github-eks > image-analysis.txt

  
  # deploy:
  #   needs: build 
  #   runs-on: self-hosted
  #   steps:
      

              





  


  

      
    


  

      
  

