name: gihub-pipeline


on:
  push:
    branches:
      - "main"




jobs:

  build:
    runs-on: self-hosted

    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./



      - name: Set up Repository 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Installing depedencies
        run: npm install


      - name: Sonar qube code analysis 
        uses: kitabisa/sonarqube-action@master
        with:
          host: ${{ secrets.SONAR_HOST_URL }}
          login: ${{ secrets.SONAR_TOKEN }}
          projectKey: "github-eks"
        

      - name: File Scan
        run: trivy fs .


      - name: Image build 
        run: |
          docker build -t inderharrysingh/github-eks:${{  github.sha }} .
          docker login -u inderharrysingh -p ${{ secrets.PASS }}
          docker push inderharrysingh/github-eks 


      - name: Image Scan
        run: trivy image  inderharrysingh/github-eks 





      
  deploy:
    runs-on: self-hosted
    needs: build

    steps:

      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

          

      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: inderharrysingh/eks-image
          token: ${{ secrets.EXTERNAL_PASS }}

      
      - name:  Chaging image
        run: sed -i 's/inderharrysingh\/eks-image:.*/inderharrysingh\/eks-image:${{ github.sha }}/' deployment.yaml

    
      - name: Pushing changes 
        run: |
          git add .
          git commit -m "updated image in response to ${{ github.sha }}"
          git push 


     



  


  

      
    


  

      
  

